# python experiments/eval/run.py  --current-dir . --dataset WebVoyager --split webvoyager/train/GitHub  --run-id 1 --simulated-user-type none --parallel 10 --config experiments/endpoint_configs/config.yaml --web-surfer-only true --use-local-browser true  --mode run --dynamic-memory-type none --dynamic-memory-file runs/MagenticUI_web_surfer_only/WebVoyager/webvoyager/train/Huggingface/1/insights/common_insights.txt
# python experiments/eval/run.py  --current-dir . --dataset WebVoyager --split webvoyager/train/GitHub  --run-id 1 --simulated-user-type none --parallel 10 --config experiments/endpoint_configs/config.yaml --web-surfer-only true --use-local-browser true  --mode run --dynamic-memory-type none --dynamic-memory-file runs/MagenticUI_web_surfer_only/WebVoyager/webvoyager/train/Huggingface/1/insights/common_insights.txt


python experiments/eval/run.py  --current-dir . --dataset WebVoyager --split webvoyager/validation/GitHub  --run-id 1 --simulated-user-type none --parallel 10 --config experiments/endpoint_configs/config.yaml --web-surfer-only true --use-local-browser true  --mode run --dynamic-memory-type none --dynamic-memory-file runs/MagenticUI_web_surfer_only/WebVoyager/webvoyager/train/Huggingface/1/insights/common_insights.txt
python experiments/eval/run.py  --current-dir . --dataset WebVoyager --split webvoyager/validation/GitHub  --run-id 1 --simulated-user-type none --parallel 10 --config experiments/endpoint_configs/config.yaml --web-surfer-only true --use-local-browser true  --mode run --dynamic-memory-type none --dynamic-memory-file runs/MagenticUI_web_surfer_only/WebVoyager/webvoyager/train/Huggingface/1/insights/common_insights.txt


python experiments/eval/run.py  --current-dir . --dataset WebVoyager --split webvoyager/train/GitHub  --run-id 1 --simulated-user-type none --parallel 10 --config experiments/endpoint_configs/config.yaml --web-surfer-only true --use-local-browser true  --mode run --dynamic-memory-type insights --dynamic-memory-file runs/MagenticUI_web_surfer_only/WebVoyager/webvoyager/train/Huggingface/1/insights/common_insights.txt
python experiments/eval/run.py  --current-dir . --dataset WebVoyager --split webvoyager/train/GitHub  --run-id 1 --simulated-user-type none --parallel 10 --config experiments/endpoint_configs/config.yaml --web-surfer-only true --use-local-browser true  --mode run --dynamic-memory-type insights --dynamic-memory-file runs/MagenticUI_web_surfer_only/WebVoyager/webvoyager/train/Huggingface/1/insights/common_insights.txt

python experiments/eval/run.py  --current-dir . --dataset WebVoyager --split webvoyager/validation/GitHub  --run-id 1 --simulated-user-type none --parallel 10 --config experiments/endpoint_configs/config.yaml --web-surfer-only true --use-local-browser true  --mode run --dynamic-memory-type insights --dynamic-memory-file runs/MagenticUI_web_surfer_only/WebVoyager/webvoyager/train/Huggingface/1/insights/common_insights.txt
python experiments/eval/run.py  --current-dir . --dataset WebVoyager --split webvoyager/validation/GitHub  --run-id 1 --simulated-user-type none --parallel 10 --config experiments/endpoint_configs/config.yaml --web-surfer-only true --use-local-browser true  --mode run --dynamic-memory-type insights --dynamic-memory-file runs/MagenticUI_web_surfer_only/WebVoyager/webvoyager/train/Huggingface/1/insights/common_insights.txt


python experiments/eval/run.py  --current-dir . --dataset WebVoyager --split webvoyager/train/GitHub  --run-id 1 --simulated-user-type none --parallel 10 --config experiments/endpoint_configs/config.yaml --web-surfer-only true --use-local-browser true  --mode run --dynamic-memory-type awm --dynamic-memory-file runs/MagenticUI_web_surfer_only/WebVoyager/webvoyager/train/Huggingface/1/workflows/common_workflows.txt
python experiments/eval/run.py  --current-dir . --dataset WebVoyager --split webvoyager/train/GitHub  --run-id 1 --simulated-user-type none --parallel 10 --config experiments/endpoint_configs/config.yaml --web-surfer-only true --use-local-browser true  --mode run --dynamic-memory-type awm --dynamic-memory-file runs/MagenticUI_web_surfer_only/WebVoyager/webvoyager/train/Huggingface/1/workflows/common_workflows.txt

python experiments/eval/run.py  --current-dir . --dataset WebVoyager --split webvoyager/validation/GitHub  --run-id 1 --simulated-user-type none --parallel 10 --config experiments/endpoint_configs/config.yaml --web-surfer-only true --use-local-browser true  --mode run --dynamic-memory-type awm --dynamic-memory-file runs/MagenticUI_web_surfer_only/WebVoyager/webvoyager/train/Huggingface/1/workflows/common_workflows.txt
python experiments/eval/run.py  --current-dir . --dataset WebVoyager --split webvoyager/validation/GitHub  --run-id 1 --simulated-user-type none --parallel 10 --config experiments/endpoint_configs/config.yaml --web-surfer-only true --use-local-browser true  --mode run --dynamic-memory-type awm --dynamic-memory-file runs/MagenticUI_web_surfer_only/WebVoyager/webvoyager/train/Huggingface/1/workflows/common_workflows.txt
