# python experiments/eval/run.py  --current-dir . --dataset WebVoyager --split webvoyager/train/Huggingface  --run-id 1 --simulated-user-type none --parallel 10 --config experiments/endpoint_configs/config.yaml --web-surfer-only true --use-local-browser true  --mode run --dynamic-memory-type insights --dynamic-memory-file runs/MagenticUI_tune_web_surfer_only_insights/WebVoyager/webvoyager/train/Huggingface/tuned_insights.txt  --system-name MagenticUI_post_tune
# python experiments/eval/run.py  --current-dir . --dataset WebVoyager --split webvoyager/train/Huggingface  --run-id 1 --simulated-user-type none --parallel 10 --config experiments/endpoint_configs/config.yaml --web-surfer-only true --use-local-browser true  --mode run --dynamic-memory-type insights --dynamic-memory-file runs/MagenticUI_tune_web_surfer_only_insights/WebVoyager/webvoyager/train/Huggingface/tuned_insights.txt  --system-name MagenticUI_post_tune
# python experiments/eval/run.py  --current-dir . --dataset WebVoyager --split webvoyager/train/Huggingface  --run-id 1 --simulated-user-type none --parallel 10 --config experiments/endpoint_configs/config.yaml --web-surfer-only true --use-local-browser true  --mode run --dynamic-memory-type insights --dynamic-memory-file runs/MagenticUI_tune_web_surfer_only_insights/WebVoyager/webvoyager/train/Huggingface/tuned_insights.txt  --system-name MagenticUI_post_tune

python experiments/eval/run.py  --current-dir . --dataset WebVoyager --split webvoyager/validation/Huggingface  --run-id 1 --simulated-user-type none --parallel 10 --config experiments/endpoint_configs/config.yaml --web-surfer-only true --use-local-browser true  --mode run --dynamic-memory-type insights --dynamic-memory-file runs/MagenticUI_tune_web_surfer_only_insights/WebVoyager/webvoyager/train/Huggingface/tuned_insights.txt  --system-name MagenticUI_post_tune
python experiments/eval/run.py  --current-dir . --dataset WebVoyager --split webvoyager/validation/Huggingface  --run-id 1 --simulated-user-type none --parallel 10 --config experiments/endpoint_configs/config.yaml --web-surfer-only true --use-local-browser true  --mode run --dynamic-memory-type insights --dynamic-memory-file runs/MagenticUI_tune_web_surfer_only_insights/WebVoyager/webvoyager/train/Huggingface/tuned_insights.txt  --system-name MagenticUI_post_tune
python experiments/eval/run.py  --current-dir . --dataset WebVoyager --split webvoyager/validation/Huggingface  --run-id 1 --simulated-user-type none --parallel 10 --config experiments/endpoint_configs/config.yaml --web-surfer-only true --use-local-browser true  --mode run --dynamic-memory-type insights --dynamic-memory-file runs/MagenticUI_tune_web_surfer_only_insights/WebVoyager/webvoyager/train/Huggingface/tuned_insights.txt  --system-name MagenticUI_post_tune

python experiments/eval/run.py  --current-dir . --dataset WebVoyager --split webvoyager/train/GitHub  --run-id 1 --simulated-user-type none --parallel 10 --config experiments/endpoint_configs/config.yaml --web-surfer-only true --use-local-browser true  --mode run --dynamic-memory-type insights --dynamic-memory-file runs/MagenticUI_tune_web_surfer_only_insights/WebVoyager/webvoyager/train/Huggingface/tuned_insights.txt  --system-name MagenticUI_post_tune
python experiments/eval/run.py  --current-dir . --dataset WebVoyager --split webvoyager/train/GitHub  --run-id 1 --simulated-user-type none --parallel 10 --config experiments/endpoint_configs/config.yaml --web-surfer-only true --use-local-browser true  --mode run --dynamic-memory-type insights --dynamic-memory-file runs/MagenticUI_tune_web_surfer_only_insights/WebVoyager/webvoyager/train/Huggingface/tuned_insights.txt  --system-name MagenticUI_post_tune
python experiments/eval/run.py  --current-dir . --dataset WebVoyager --split webvoyager/train/GitHub  --run-id 1 --simulated-user-type none --parallel 10 --config experiments/endpoint_configs/config.yaml --web-surfer-only true --use-local-browser true  --mode run --dynamic-memory-type insights --dynamic-memory-file runs/MagenticUI_tune_web_surfer_only_insights/WebVoyager/webvoyager/train/Huggingface/tuned_insights.txt  --system-name MagenticUI_post_tune

python experiments/eval/run.py  --current-dir . --dataset WebVoyager --split webvoyager/validation/GitHub  --run-id 1 --simulated-user-type none --parallel 10 --config experiments/endpoint_configs/config.yaml --web-surfer-only true --use-local-browser true  --mode run --dynamic-memory-type insights --dynamic-memory-file runs/MagenticUI_tune_web_surfer_only_insights/WebVoyager/webvoyager/train/Huggingface/tuned_insights.txt  --system-name MagenticUI_post_tune
python experiments/eval/run.py  --current-dir . --dataset WebVoyager --split webvoyager/validation/GitHub  --run-id 1 --simulated-user-type none --parallel 10 --config experiments/endpoint_configs/config.yaml --web-surfer-only true --use-local-browser true  --mode run --dynamic-memory-type insights --dynamic-memory-file runs/MagenticUI_tune_web_surfer_only_insights/WebVoyager/webvoyager/train/Huggingface/tuned_insights.txt  --system-name MagenticUI_post_tune
python experiments/eval/run.py  --current-dir . --dataset WebVoyager --split webvoyager/validation/GitHub  --run-id 1 --simulated-user-type none --parallel 10 --config experiments/endpoint_configs/config.yaml --web-surfer-only true --use-local-browser true  --mode run --dynamic-memory-type insights --dynamic-memory-file runs/MagenticUI_tune_web_surfer_only_insights/WebVoyager/webvoyager/train/Huggingface/tuned_insights.txt  --system-name MagenticUI_post_tune
