python experiments/eval/run.py  --current-dir . --dataset WebVoyager --split webvoyager/train  --run-id 1 --simulated-user-type none --parallel 500 --config experiments/endpoint_configs/multi_config.yaml --web-surfer-only true --use-local-browser true  --mode eval --dynamic-memory-type none --dynamic-memory-file runs/MagenticUI_tune_web_surfer_only_insights/WebVoyager/webvoyager/train/Huggingface/tuned_insights.txt  --system-name MagenticUI --redo-eval --subsample 0.3 --seed 7
python experiments/eval/run.py  --current-dir . --dataset WebVoyager --split webvoyager/train  --run-id 2 --simulated-user-type none --parallel 500 --config experiments/endpoint_configs/multi_config.yaml --web-surfer-only true --use-local-browser true  --mode eval --dynamic-memory-type none --dynamic-memory-file runs/MagenticUI_tune_web_surfer_only_insights/WebVoyager/webvoyager/train/Huggingface/tuned_insights.txt  --system-name MagenticUI --redo-eval --subsample 0.3 --seed 7
python experiments/eval/run.py  --current-dir . --dataset WebVoyager --split webvoyager/train  --run-id 3 --simulated-user-type none --parallel 500 --config experiments/endpoint_configs/multi_config.yaml --web-surfer-only true --use-local-browser true  --mode eval --dynamic-memory-type none --dynamic-memory-file runs/MagenticUI_tune_web_surfer_only_insights/WebVoyager/webvoyager/train/Huggingface/tuned_insights.txt  --system-name MagenticUI --redo-eval --subsample 0.3 --seed 7
python experiments/eval/run.py  --current-dir . --dataset WebVoyager --split webvoyager/train  --run-id 4 --simulated-user-type none --parallel 500 --config experiments/endpoint_configs/multi_config.yaml --web-surfer-only true --use-local-browser true  --mode eval --dynamic-memory-type none --dynamic-memory-file runs/MagenticUI_tune_web_surfer_only_insights/WebVoyager/webvoyager/train/Huggingface/tuned_insights.txt  --system-name MagenticUI --redo-eval --subsample 0.3 --seed 7
python experiments/eval/run.py  --current-dir . --dataset WebVoyager --split webvoyager/train  --run-id 5 --simulated-user-type none --parallel 500 --config experiments/endpoint_configs/multi_config.yaml --web-surfer-only true --use-local-browser true  --mode eval --dynamic-memory-type none --dynamic-memory-file runs/MagenticUI_tune_web_surfer_only_insights/WebVoyager/webvoyager/train/Huggingface/tuned_insights.txt  --system-name MagenticUI --redo-eval --subsample 0.3 --seed 7

# python experiments/eval/run.py  --current-dir . --dataset WebVoyager --split webvoyager/test  --run-id 1 --simulated-user-type none --parallel 50 --config experiments/endpoint_configs/multi_config.yaml --web-surfer-only true --use-local-browser true  --mode run --dynamic-memory-type none --dynamic-memory-file runs/MagenticUI_tune_web_surfer_only_insights/WebVoyager/webvoyager/train/Huggingface/tuned_insights.txt  --system-name MagenticUI --redo-eval
# python experiments/eval/run.py  --current-dir . --dataset WebVoyager --split webvoyager/test  --run-id 1 --simulated-user-type none --parallel 50 --config experiments/endpoint_configs/multi_config.yaml --web-surfer-only true --use-local-browser true  --mode run --dynamic-memory-type none --dynamic-memory-file runs/MagenticUI_tune_web_surfer_only_insights/WebVoyager/webvoyager/train/Huggingface/tuned_insights.txt  --system-name MagenticUI
# python experiments/eval/run.py  --current-dir . --dataset WebVoyager --split webvoyager/test  --run-id 1 --simulated-user-type none --parallel 50 --config experiments/endpoint_configs/multi_config.yaml --web-surfer-only true --use-local-browser true  --mode run --dynamic-memory-type none --dynamic-memory-file runs/MagenticUI_tune_web_surfer_only_insights/WebVoyager/webvoyager/train/Huggingface/tuned_insights.txt  --system-name MagenticUI
