python experiments/eval/run.py  --current-dir . --dataset WebVoyager --split webvoyager/train/Huggingface  --run-id 1 --simulated-user-type none --parallel 10 --config experiments/endpoint_configs/config.yaml --web-surfer-only true --use-local-browser true  --mode run --dynamic-memory-type insights --dynamic-memory-file runs/MagenticUI_web_surfer_only/WebVoyager/webvoyager/train/Huggingface/1/insights/common_insights_2.txt --system-name MagenticUI_evidence
python experiments/eval/run.py  --current-dir . --dataset WebVoyager --split webvoyager/train/Huggingface  --run-id 1 --simulated-user-type none --parallel 10 --config experiments/endpoint_configs/config.yaml --web-surfer-only true --use-local-browser true  --mode run --dynamic-memory-type insights --dynamic-memory-file runs/MagenticUI_web_surfer_only/WebVoyager/webvoyager/train/Huggingface/1/insights/common_insights_2.txt --system-name MagenticUI_evidence

python experiments/eval/run.py  --current-dir . --dataset WebVoyager --split webvoyager/validation/Huggingface  --run-id 1 --simulated-user-type none --parallel 10 --config experiments/endpoint_configs/config.yaml --web-surfer-only true --use-local-browser true  --mode run --dynamic-memory-type insights --dynamic-memory-file runs/MagenticUI_web_surfer_only/WebVoyager/webvoyager/train/Huggingface/1/insights/common_insights_2.txt --system-name MagenticUI_evidence
python experiments/eval/run.py  --current-dir . --dataset WebVoyager --split webvoyager/validation/Huggingface  --run-id 1 --simulated-user-type none --parallel 10 --config experiments/endpoint_configs/config.yaml --web-surfer-only true --use-local-browser true  --mode run --dynamic-memory-type insights --dynamic-memory-file runs/MagenticUI_web_surfer_only/WebVoyager/webvoyager/train/Huggingface/1/insights/common_insights_2.txt --system-name MagenticUI_evidence

python experiments/eval/run.py  --current-dir . --dataset WebVoyager --split webvoyager/train/GitHub  --run-id 1 --simulated-user-type none --parallel 10 --config experiments/endpoint_configs/config.yaml --web-surfer-only true --use-local-browser true  --mode run --dynamic-memory-type insights --dynamic-memory-file runs/MagenticUI_web_surfer_only/WebVoyager/webvoyager/train/Huggingface/1/insights/common_insights_2.txt --system-name MagenticUI_evidence
python experiments/eval/run.py  --current-dir . --dataset WebVoyager --split webvoyager/train/GitHub  --run-id 1 --simulated-user-type none --parallel 10 --config experiments/endpoint_configs/config.yaml --web-surfer-only true --use-local-browser true  --mode run --dynamic-memory-type insights --dynamic-memory-file runs/MagenticUI_web_surfer_only/WebVoyager/webvoyager/train/Huggingface/1/insights/common_insights_2.txt --system-name MagenticUI_evidence

python experiments/eval/run.py  --current-dir . --dataset WebVoyager --split webvoyager/validation/GitHub  --run-id 1 --simulated-user-type none --parallel 10 --config experiments/endpoint_configs/config.yaml --web-surfer-only true --use-local-browser true  --mode run --dynamic-memory-type insights --dynamic-memory-file runs/MagenticUI_web_surfer_only/WebVoyager/webvoyager/train/Huggingface/1/insights/common_insights_2.txt --system-name MagenticUI_evidence
python experiments/eval/run.py  --current-dir . --dataset WebVoyager --split webvoyager/validation/GitHub  --run-id 1 --simulated-user-type none --parallel 10 --config experiments/endpoint_configs/config.yaml --web-surfer-only true --use-local-browser true  --mode run --dynamic-memory-type insights --dynamic-memory-file runs/MagenticUI_web_surfer_only/WebVoyager/webvoyager/train/Huggingface/1/insights/common_insights_2.txt --system-name MagenticUI_evidence





python experiments/eval/run.py  --current-dir . --dataset WebVoyager --split webvoyager/train/Huggingface  --run-id 1 --simulated-user-type none --parallel 10 --config experiments/endpoint_configs/config.yaml --web-surfer-only true --use-local-browser true  --mode run --dynamic-memory-type insights --dynamic-memory-file runs/MagenticUI_web_surfer_only/WebVoyager/webvoyager/train/Huggingface/1/insights/common_insights_failures.txt --system-name MagenticUI_failures
python experiments/eval/run.py  --current-dir . --dataset WebVoyager --split webvoyager/train/Huggingface  --run-id 1 --simulated-user-type none --parallel 10 --config experiments/endpoint_configs/config.yaml --web-surfer-only true --use-local-browser true  --mode run --dynamic-memory-type insights --dynamic-memory-file runs/MagenticUI_web_surfer_only/WebVoyager/webvoyager/train/Huggingface/1/insights/common_insights_failures.txt --system-name MagenticUI_failures

python experiments/eval/run.py  --current-dir . --dataset WebVoyager --split webvoyager/validation/Huggingface  --run-id 1 --simulated-user-type none --parallel 10 --config experiments/endpoint_configs/config.yaml --web-surfer-only true --use-local-browser true  --mode run --dynamic-memory-type insights --dynamic-memory-file runs/MagenticUI_web_surfer_only/WebVoyager/webvoyager/train/Huggingface/1/insights/common_insights_failures.txt --system-name MagenticUI_failures
python experiments/eval/run.py  --current-dir . --dataset WebVoyager --split webvoyager/validation/Huggingface  --run-id 1 --simulated-user-type none --parallel 10 --config experiments/endpoint_configs/config.yaml --web-surfer-only true --use-local-browser true  --mode run --dynamic-memory-type insights --dynamic-memory-file runs/MagenticUI_web_surfer_only/WebVoyager/webvoyager/train/Huggingface/1/insights/common_insights_failures.txt --system-name MagenticUI_failures

python experiments/eval/run.py  --current-dir . --dataset WebVoyager --split webvoyager/train/GitHub  --run-id 1 --simulated-user-type none --parallel 10 --config experiments/endpoint_configs/config.yaml --web-surfer-only true --use-local-browser true  --mode run --dynamic-memory-type insights --dynamic-memory-file runs/MagenticUI_web_surfer_only/WebVoyager/webvoyager/train/Huggingface/1/insights/common_insights_failures.txt --system-name MagenticUI_failures
python experiments/eval/run.py  --current-dir . --dataset WebVoyager --split webvoyager/train/GitHub  --run-id 1 --simulated-user-type none --parallel 10 --config experiments/endpoint_configs/config.yaml --web-surfer-only true --use-local-browser true  --mode run --dynamic-memory-type insights --dynamic-memory-file runs/MagenticUI_web_surfer_only/WebVoyager/webvoyager/train/Huggingface/1/insights/common_insights_failures.txt --system-name MagenticUI_failures

python experiments/eval/run.py  --current-dir . --dataset WebVoyager --split webvoyager/validation/GitHub  --run-id 1 --simulated-user-type none --parallel 10 --config experiments/endpoint_configs/config.yaml --web-surfer-only true --use-local-browser true  --mode run --dynamic-memory-type insights --dynamic-memory-file runs/MagenticUI_web_surfer_only/WebVoyager/webvoyager/train/Huggingface/1/insights/common_insights_failures.txt --system-name MagenticUI_failures
python experiments/eval/run.py  --current-dir . --dataset WebVoyager --split webvoyager/validation/GitHub  --run-id 1 --simulated-user-type none --parallel 10 --config experiments/endpoint_configs/config.yaml --web-surfer-only true --use-local-browser true  --mode run --dynamic-memory-type insights --dynamic-memory-file runs/MagenticUI_web_surfer_only/WebVoyager/webvoyager/train/Huggingface/1/insights/common_insights_failures.txt --system-name MagenticUI_failures

